name: lost_and_found
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayer: ^0.5.2
  audioplayers: ^0.12.1
  flutter_sound: ^1.0.6
  intro_slider: ^2.2.0
  flip_panel: 1.0.0
  flutter_swiper : ^1.1.6
  shimmer: 1.0.0

  animated_splash: ^1.0.0

  page_transition: '^1.1.0'


  webview_flutter: ^0.3.0
  photo_view: 0.2.4
  progress_dialog: ^1.1.0+1
  animated_text_kit: ^1.3.1

  flutter_localizations:
    sdk: flutter

  url_launcher: ^4.0.2
  share: ^0.6.0+1
  http: ^0.12.0
  introduction_screen: ^1.0.5+1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flip_card: 0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/place_holder.jpg
    - assets/place_holder_2.jpg
    - assets/place_holder_3.jpg
    - assets/logo.png
    - assets/system/mainEX.jpg
    - assets/person/image01.jpg
    - assets/person/image02.jpg
    - assets/person/image03.jpg
    - assets/person/image04.jpg
    - assets/person/image05.jpg
    - assets/person/image06.jpg
    - assets/person/image07.jpg
    - assets/person/image08.jpg
    - assets/person/image09.jpg
    - assets/person/image10.jpg
    - assets/person/image11.jpg
    - assets/person/j1.png
    - assets/person/j2.png
    - assets/person/j3.png
    - assets/person/j4.png
    - assets/person/p1.png
    - assets/person/p2.png
    - assets/person/p3.png
    - assets/person/p4.png
    - assets/person/p5.png
    - assets/person/p6.png
    - assets/system/Logo_gif.gif
    - assets/system/intro1.png
    - assets/system/intro2.png
    - assets/system/intro3.png
    - assets/system/intro4.png
    - assets/system/soundBtn1.png
    - assets/system/soundBtn2.png
    - assets/system/nextBtn1.png
    - assets/system/backBtn1.png
    - assets/audios/
    - assets/audios/Theme_full.mp3
    - assets/system/i1.png
    - assets/system/i2.png
    - assets/system/i3.png
    - assets/system/i4.png
    - assets/system/star.png
    - assets/splash.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
